Import("env")

import subprocess
from os.path import join

def get_git_rev():
    git_rev = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"]).decode().strip()
    git_status = subprocess.check_output(["git", "status", "-s", "--untracked-files=no"]).decode()
    suffix = "dirty" if git_status else ""

    return git_rev + suffix

def get_version():
    with open("src/OC_version.h") as file:
        last_line = file.readlines()[-1].strip().replace('"', '')

    return last_line 

git_rev = get_git_rev()
env.Append(BUILD_FLAGS=[ f'-DOC_BUILD_TAG=\\"{git_rev}\\"' ])

def after_build(source, target, env):
    """Stitches the multiboot hex and OVERRITES firmware.hex in-place
    so the upload target picks up the combined 3-slot hex."""
    git_rev = get_git_rev()
    version = get_version()
    build_flags = env.ParseFlags(env['BUILD_FLAGS'])
    defines = build_flags.get("CPPDEFINES")
    for item in defines:
        if item[0] == 'OC_VERSION_EXTRA':
            version += item[1].strip('"')

    import os
    project_dir = env.subst("$PROJECT_DIR")
    build_dir = os.path.join(project_dir, ".pio/build/T41_MTP")
    app_A = os.path.join(project_dir, ".pio/build/T41/firmware.hex")
    app_B = os.path.join(project_dir, ".pio/build/T41_audio/firmware.hex")
    app_X = os.path.join(build_dir, "firmware.hex")

    # Verify all input files exist before stitching
    for f, name in [(app_A, "T41 (Slot B)"), (app_B, "T41_audio (Slot A)"), (app_X, "T41_MTP (Slot X)")]:
        if not os.path.exists(f):
            print(f"ERROR: {name} hex file not found: {f}")
            print("Multiboot stitching FAILED. Build all 3 environments together:")
            print("  pio run -e T41_audio -e T41 -e T41_MTP")
            import sys
            sys.exit(1)
        else:
            print(f"OK: {name} found ({os.path.getsize(f)} bytes)")

    # Stitch all 3 slots into firmware.hex IN-PLACE
    out = os.path.join(build_dir, "firmware.hex")

    platform = env.PioPlatform()
    srec_cat = join(platform.get_package_dir("tool-sreccat") or "", "srec_cat")
    result = subprocess.call([srec_cat, app_A, "-Intel", app_B, "-Intel", app_X, "-Intel", "-o", out, "-Intel"])

    if result != 0:
        print(f"ERROR: srec_cat failed with exit code {result}")
        import sys
        sys.exit(1)

    if os.path.exists(out):
        stitched_size = os.path.getsize(out)
        is_multiboot = stitched_size > 2_000_000  # 3.3MB vs 973KB
        if is_multiboot:
            print(f"Multiboot hex stitched successfully (firmware.hex): {stitched_size} bytes")
            # Also save a labeled copy for reference / direct Teensy Loader use
            label = f"o_C-phazerville-{version}-{git_rev}.hex"
            import shutil
            shutil.copy2(out, os.path.join(build_dir, label))
        else:
            print(f"ERROR: Stitched hex is only {stitched_size} bytes (expected >3MB). Stitching FAILED.")
            import sys
            sys.exit(1)
    else:
        print("ERROR: srec_cat succeeded but output file not found")
        import sys
        sys.exit(1)

def pre_upload(source, target, env):
    """Runs RIGHT BEFORE upload. If firmware.hex is already stitched (>2MB),
    just verify it. If it was regenerated by PIO (<2MB), re-stitch if T41_audio exists."""
    import os
    build_dir = os.path.join(env.subst("$PROJECT_DIR"), ".pio/build/T41_MTP")
    firmware_hex = os.path.join(build_dir, "firmware.hex")
    app_B = os.path.join(env.subst("$PROJECT_DIR"), ".pio/build/T41_audio/firmware.hex")

    if not os.path.exists(firmware_hex):
        print("ERROR: firmware.hex not found")
        import sys
        sys.exit(1)

    size = os.path.getsize(firmware_hex)
    if size < 2_000_000:
        # PIO regenerated from .elf — re-stitch if T41_audio exists
        if os.path.exists(app_B):
            print(f"WARNING: firmware.hex regenerated by PIO ({size} bytes), re-stitching...")
            after_build(source, target, env)
        else:
            print(f"WARNING: firmware.hex is {size} bytes (single-slot) and T41_audio not found.")
            print("Using pre-stitched firmware.hex if available.")
    else:
        print(f"Multiboot firmware.hex OK ({size} bytes)")

# Hook 1: Stitch after buildprog completes
env.AddPostAction("buildprog", after_build)

# Hook 2: Re-check right before upload in case PIO regenerated firmware.hex
# This catches the case where `pio run -e T41_MTP -t upload` rebuilds+uploads in one step
env.AddPreAction("upload", pre_upload)
