; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src
default_envs =
;  T32
;  T32_vor
  T40
  nlm_cardoc_T40
  T41
  T41_audio
  T41_MTP

[env]
framework = arduino
platform = https://github.com/platformio/platform-teensy.git#v5.1.1
platform_packages =
  tool-teensy
;  framework-arduinoteensy @ 1.159.0
  framework-arduinoteensy @ https://github.com/djphazer/framework-arduinoteensy.git#14937d2d3a28365b91adab9d77d750c4d152d637
  tool-sreccat
build_flags =
  -DTEENSY_OPT_SMALLEST_CODE
  -DUSB_MIDI
;  -DUSB_MIDI_AUDIO_SERIAL
;  -DUSB_MIDI_SERIAL
;    -DOC_DEV
;    -DPRINT_DEBUG
  -Isrc/extern
  -fno-exceptions
  -falign-functions=32
  -falign-loops=32
  -falign-jumps=32
  -Wall
  -Wfatal-errors
;  -Wl,-Map,firmware.map
;  -Wconversion
;  -Wextra
;  -Werror

extra_scripts = pre:res/progname.py

upload_protocol = teensy-gui

[env:T3]
extends = env
board = teensy31
board_build.f_cpu = 120000000
lib_deps = EEPROM
lib_ignore = USBHost_t36, Audio, Wire, SPI, SD, LittleFS, SerialFlash

[env:custom]
extends = env:T3
build_flags =
    ${env.build_flags}
    ${sysenv.CUSTOM_BUILD_FLAGS}
    -DOC_VERSION_EXTRA="\"_custom\""

[env:T4]
build_flags =
  ${env.build_flags}
;  -DPEWPEWPEW
  -DTEENSY_OPT_SMALLEST_CODE_LTO
  -DGATEMAP_GRIDS2
  -DENABLE_APP_CALIBR8OR
  -DENABLE_APP_SCENES
  -DENABLE_APP_ENIGMA
  -DENABLE_APP_MIDI
  -DENABLE_APP_PONG
  -DENABLE_APP_PIQUED
  -DENABLE_APP_POLYLFO
  -DENABLE_APP_H1200
  -DENABLE_APP_BYTEBEATGEN
  -DENABLE_APP_NEURAL_NETWORK
  -DENABLE_APP_DARKEST_TIMELINE
  -DENABLE_APP_LORENZ
  -DENABLE_APP_ASR
  -DENABLE_APP_QUANTERMAIN
  -DENABLE_APP_METAQ
  -DENABLE_APP_CHORDS
  -DENABLE_APP_PASSENCORE
  -DENABLE_APP_SEQUINS
  -DENABLE_APP_AUTOMATONNETZ
  -DENABLE_APP_BBGEN
;  -DENABLE_APP_REFERENCES

[env:T40]
board = teensy40
board_build.f_cpu = 300000000
lib_ignore = Audio, Wire
build_flags = ${env:T4.build_flags}
  -DOC_VERSION_EXTRA="\"_T40\""

[env:T41]
board = teensy41
board_build.f_cpu = 600000000
board_build.ldscript = slot1.ld
build_flags = ${env.build_flags}
; -DPEWPEWPEW
  -DTEENSY_OPT_SMALLEST_CODE_LTO
  -Iteensy-variable-playback/src
  -falign-functions=32
  -falign-loops=32
  -falign-jumps=32
  -DGATEMAP_GRIDS2
  -DENABLE_APP_CALIBR8OR
  -DENABLE_APP_SCENES
;  -DENABLE_APP_MIDI
  -DENABLE_APP_PONG
;  -DENABLE_APP_PIQUED
;  -DENABLE_APP_POLYLFO
;  -DENABLE_APP_BYTEBEATGEN
;  -DENABLE_APP_REFERENCES
;  -DENABLE_APP_BBGEN
;  -DENABLE_APP_PASSENCORE
;  -DENABLE_APP_AUTOMATONNETZ
;  -DENABLE_APP_LORENZ
;  -DENABLE_APP_SEQUINS
;  -DENABLE_APP_H1200
;  -DENABLE_APP_QUANTERMAIN
  -DOC_VERSION_EXTRA="\"_T41\""

build_src_filter = +<*> +<../teensy-variable-playback/src/*.cpp>

[env:T41_audio]
extends = env:T41
board_build.ldscript = slot0.ld
build_flags =
  ${env:T41.build_flags}
  -DMULTIBOOT
  -DUSB_AUDIO
extra_scripts = pre:res/patch_psram.py
[env:T41_MTP]
extends = env:T41
board_build.ldscript = slot2.ld
build_flags = ${env.build_flags}
  -DTEENSY_OPT_SMALLEST_CODE_LTO
  -DUSB_MTPDISK
  -DNO_HEMISPHERE
; stock apps
  -DENABLE_APP_ASR
  -DENABLE_APP_QUANTERMAIN
  -DENABLE_APP_METAQ
  -DENABLE_APP_CHORDS
  -DENABLE_APP_SEQUINS
  -DENABLE_APP_AUTOMATONNETZ
  -DENABLE_APP_LORENZ
  -DENABLE_APP_PIQUED
  -DENABLE_APP_POLYLFO
  -DENABLE_APP_H1200
  -DENABLE_APP_BYTEBEATGEN
  -DENABLE_APP_BBGEN
  -DENABLE_APP_REFERENCES
; HS Apps
  -DENABLE_APP_ENIGMA
  -DENABLE_APP_MIDI
  -DENABLE_APP_NEURAL_NETWORK
  -DENABLE_APP_DARKEST_TIMELINE
  -DENABLE_APP_PONG
; extra
  -DENABLE_APP_PASSENCORE
  -DENABLE_APP_CALIBR8OR
  -DENABLE_APP_SCENES
  -nostartfiles
  -nostdlib
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -DOC_VERSION_EXTRA="\"_T41\""

extra_scripts = post:res/assemble-multiboot.py

[env:T41_dev]
extends = env:T41
lib_deps =
  https://github.com/djphazer/teensy-variable-playback.git#debug
  https://github.com/PaulStoffregen/Audio#3039be2773e86daf1f381a1e8bdc1e6a55ed11f1
build_flags =
  ${env:T41.build_flags} -DOC_DEV
  -DPRINT_DEBUG
  -UENABLE_APP_POLYLFO

[env:antihem]
extends = env:T3
build_flags =
  ${env.build_flags}
  -DNO_HEMISPHERE
  -DENABLE_APP_CALIBR8OR
  -DENABLE_APP_SCENES
;  -DENABLE_APP_ENIGMA
  -DENABLE_APP_MIDI
  -DENABLE_APP_PONG
;  -DENABLE_APP_PIQUED
;  -DENABLE_APP_POLYLFO
;  -DENABLE_APP_H1200
;  -DENABLE_APP_BYTEBEATGEN
;  -DENABLE_APP_NEURAL_NETWORK
  -DENABLE_APP_DARKEST_TIMELINE
  -DENABLE_APP_LORENZ
;  -DENABLE_APP_ASR
;  -DENABLE_APP_QUANTERMAIN
;  -DENABLE_APP_METAQ
;  -DENABLE_APP_CHORDS
  -DENABLE_APP_PASSENCORE
;  -DENABLE_APP_SEQUINS
;  -DENABLE_APP_AUTOMATONNETZ
  -DENABLE_APP_BBGEN
  -DENABLE_APP_REFERENCES

[env:stock]
extends = env:T3
build_flags =
  ${env.build_flags}
  -DNO_HEMISPHERE
  -DENABLE_APP_ASR
  -DENABLE_APP_QUANTERMAIN
  -DENABLE_APP_METAQ
  -DENABLE_APP_CHORDS
  -DENABLE_APP_SEQUINS
  -DENABLE_APP_AUTOMATONNETZ
  -DENABLE_APP_LORENZ
  -DENABLE_APP_PIQUED
  -DENABLE_APP_POLYLFO
  -DENABLE_APP_H1200
  -DENABLE_APP_BYTEBEATGEN
  -DENABLE_APP_BBGEN
  -DENABLE_APP_REFERENCES
  -DENABLE_APP_PONG
  -DENABLE_APP_PASSENCORE
  -DOC_VERSION_EXTRA="\"_T32+stock\""

[env:stock_vor]
extends = env:T3
build_flags =
  ${env:stock.build_flags}
  -DVOR

[env:T32]
extends = env:T3
build_flags =
    ${env.build_flags}
    -DENABLE_APP_CALIBR8OR
    -DENABLE_APP_SCENES
;    -DENABLE_APP_QUANTERMAIN
;    -DENABLE_APP_ENIGMA
;    -DENABLE_APP_MIDI
    -DENABLE_APP_PONG
;    -DENABLE_APP_PIQUED
;    -DENABLE_APP_POLYLFO
;    -DENABLE_APP_PASSENCORE
;    -DENABLE_APP_H1200
;    -DENABLE_APP_BYTEBEATGEN
;    -DENABLE_APP_BBGEN
;    -DENABLE_APP_REFERENCES
;    -DENABLE_APP_NEURAL_NETWORK
;    -DENABLE_APP_DARKEST_TIMELINE
    -DGATEMAP_GRIDS2
;    -DPEWPEWPEW
    -DOC_VERSION_EXTRA="\"_T32\""

[env:T32_vor]
extends = env:T3
build_flags =
    ${env:T32.build_flags}
    -DVOR


; --- Builds for Northern Light Modular 4U Buchla format
; default apps for NLM builds
[env:nlm]
extends = env:T3
build_flags =
    ${env.build_flags}
    -DGATEMAP_GRIDS2
    -DENABLE_APP_CALIBR8OR
    -DENABLE_APP_SCENES
;    -DENABLE_APP_ENIGMA
    -DENABLE_APP_PONG
    -DENABLE_APP_PIQUED
    -DENABLE_APP_POLYLFO
;    -DENABLE_APP_PASSENCORE
;    -DENABLE_APP_H1200
;    -DENABLE_APP_BYTEBEATGEN
;    -DENABLE_APP_BBGEN
    -DNORTHERNLIGHT

[env:nlm_T40]
extends = env:T40
build_flags =
    ${env:T4.build_flags}
    -DNORTHERNLIGHT

; for old versions without inverted outputs
[env:nlm_diy]
extends = env:nlm
build_flags =
    ${env:nlm.build_flags}
    -DNLM_DIY
    -DOC_VERSION_EXTRA="\"_NLM-DIY\""

; for the 2OC 4U module, right side
[env:nlm_right]
extends = env:nlm
build_flags =
    ${env:nlm.build_flags}
    -DOC_VERSION_EXTRA="\"_NLM-2OC_R\""

; for the 2OC 4U module, left side
[env:nlm_left]
extends = env:nlm
build_flags =
    ${env:nlm.build_flags}
    -DNORTHERNLIGHT_2OC_LEFTSIDE
    -DOC_VERSION_EXTRA="\"_NLM-2OC_L\""

; for the hOC module
[env:nlm_hoc]
extends = env:nlm
build_flags =
    ${env:nlm.build_flags}
    -DNLM_hOC
    -DOC_VERSION_EXTRA="\"_NLM-hOC\""
[env:nlm_hoc_T40]
extends = env:nlm_T40
build_flags =
    ${env:nlm_T40.build_flags}
    -DNLM_hOC
    -DOC_VERSION_EXTRA="\"_NLM+hOC\""

; for the cOC Easel card
[env:nlm_cardoc]
extends = env:nlm
build_flags =
    ${env:nlm.build_flags}
    -DNLM_cardOC
    -DOC_VERSION_EXTRA="\"_NLM-cardOC\""
[env:nlm_cardoc_T40]
extends = env:nlm_T40
build_flags =
    ${env:nlm_T40.build_flags}
    -DNLM_cardOC
    -DOC_VERSION_EXTRA="\"_NLM+cardOC\""

[env:oc_dev]
extends = env:T3
build_flags = ${env.build_flags} -DOC_DEV
; -DPRINT_DEBUG
